# Birds CUB dataset
birds_images_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/birds dataset/images/'
birds_embedding_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/birds dataset/'
birds_text_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/birds dataset/word_c10/'
birds_dataset_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/birds dataset/text2image/birds.hdf5'
val_split_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/birds dataset/valclasses.txt'
train_split_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/birds dataset/trainclasses.txt'
test_split_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/birds dataset/testclasses.txt'


# flowers dataset
flowers_images_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/flower dataset/'
flowers_embedding_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/flower dataset/'
flowers_text_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/flower dataset/text_c10/'
flowers_dataset_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/flower dataset/text2image/flowers.hdf5'

flowers_val_split_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/flower dataset/valclasses.txt'
flowers_train_split_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/flower dataset/trainclasses.txt'
flowers_test_split_path: '/mnt/codebox/Text-to-Image-Synthesis/datasets/flower dataset/testclasses.txt'
